### ISSUE TITLE
Can't Connect At All Anymore

### ISSUE THREAD

**Issue by phoofboy** [rcuhljr/dr-lich#16]
So after following the steps for setting this up the game immediately disconnects when trying to use Genie or Stormfront, even if I run the ruby command that listens for the port 4001 etc.

**Comment by rcuhljr** [comment]
Most likely lich was killed while it was waiting for a connection. You'll want to check your HOSTS file and remove any lich redirects that may be there. [More details](https://www.reddit.com/r/dragonrealms/comments/55souh/lich_on_mac_now_none_of_my_fes_work/d8di25g/)

**Comment by phoofboy** [comment]
Awesome, thanks. Was digging through the firewall for rules, looking at fiddler and seeing nothing.
