### ISSUE TITLE
Barb Meditations

### ISSUE THREAD

**Issue by RyanEOD** [rcuhljr/dr-lich#37]
In base-spells.yaml the Barb Meditations have their activated messages of when you start the meditation. Without the Yogi Mastery, it still takes a few seconds to complete after the round time before you can stand up. So, can we change the Meditations from;

`    activated_message: ^You .* to meditate`

to 

`    activated_message: feel a jolt as your vision snaps shut`

I've edited them all in the attached base-spells.yaml but I'm not quite sure how to get it added to the "base" so my file doesn't keep getting updated locally.  
[base-spells.zip](https://github.com/rcuhljr/dr-lich/files/2453420/base-spells.zip)

Thanks!

**Comment by Tarhish** [comment]
Could you please close this issue and copy it over on https://github.com/rpherbig/dr-scripts/issues ?

This fork is more for the lich program itself rather than the scripts in it, and more people will see it over there.

**Comment by RyanEOD** [comment]
Thank you, I'm new to submitting things here, done done and closing!
