### ISSUE TITLE
Port 4901 or 4091?

### ISSUE THREAD

**Issue by TheCharlesChen** [rcuhljr/dr-lich#38]
It seems in the latest version, the gameport = 4901 was changed to 4091.  Is this correct or is this a typo.  This would certainly cause issues in connection if it's the case.

**Comment by rcuhljr** [comment]
I'm not exactly certain what you mean by latest version, but we've been running with 4091 for a couple of years now I believe. I know it was a purposeful change from the old port in lich mainline, I don't remember the reasoning anymore.

**Comment by rcuhljr** [comment]
It should be noted that the port that actually matters if I'm remembering correctly is the `11024` port for DR.

**Comment by TheCharlesChen** [comment]
OK, I confirm that the port 4901 and 4091 are irrelevant.  I noticed that the 4901 on line 10561 has been updated to reflect the port 11024.  This works.

Next question, when running frostbite, there's a repo update that happens after startup that seems to revert lich back to 4.6.49:

[repository: Lich has been updated to version 4.6.49.]
[repository: Changes will take effect next time you start Lich.]
[repository: downloading map database...]

I'm using the 4.6.49 data files with this fork of the .rbw

**Comment by rcuhljr** [comment]
Yeah, that will happen if you haven't switched to this fork via dependency.lic. You can manually disable the repository update of lich with something like `;repository unset-lich-updatable`

**Comment by TheCharlesChen** [comment]
I finally got this to work!  FYI I'm working on Mac OSX Mojave 10.14.3 
1) Installed lich 4.6.49
2) Cloned this Git repo and pulled the .rbw out and overwrite the 4.6.49 version.
3) Changed port back to 4901. (not sure this did anything)
4) Updated Ruby to 2.3.0 and 'set rbenv local 2.3.0'
5) Reinstalled sqlite3: 'sudo gem install sqlite3'
6) Start lich: 'sudo ruby ./lich/lich.rbw --dragonrealms --frostbite
7) Download license file ;repository download dependency.lic
8) Trust Dependency failed, but I think it doesn't matter: ;trust dependency
9) Install dependency.  This took about 5 minutes. : ;dependency install
10) Use fork: ;e use_lich_fork
11) Restart Lich
12) I had to repeat step 2 because the Lich had replaced with 4.6.49 on first startup
13) After restart, Lich used the new fork and updated properly.

Step 4 was critical.  Before this it kept opening the ruby script in a separate exec terminal and wouldn't run unless I clicked the exec window repeatedly.

**Comment by TheCharlesChen** [comment]
As a P.S. comment, GTK2 was causing problems on Mac because it was opening the executable terminal window separately which required the executable window to be active in order to function.  Uninstalling GTK2 and running Frostbite solved the problem.
