### ISSUE TITLE
repository isn't updating automatically at startup

### ISSUE THREAD

**Issue by lucianposton** [rcuhljr/dr-lich#46]
![img-2020-04-02T21:27:05 237Z](https://user-images.githubusercontent.com/646121/78301707-1a99f000-74ff-11ea-855c-0201bf561414.png)

Some error is causing repository to not receive the `download-updates` argument as expected. It appears to be in the sqlite db as expected, however. I tried deleting the sqlite dbs so the autostarts are repopulated, and also tried reinstalling dr-lich.

**Comment by BinuDR** [comment]
try this
`;repos download autostart.lic`
Then log out and back in

**Comment by lucianposton** [comment]
@BinuDR thanks. That fixed it. My old `autostart.lic` was passing `['download-updates']` as an Array. After doing `;repos download autostart.lic`, the args ended up being passed to the Script object as a String instead, and the code path for Strings works correctly.

While trying to figure this issue out, I stumbled across a TODO in the code for the Array code path that was easy enough to fix to get it working, so I sent a pr for that if you guys are interested. Feel free to close this if you don't want to pr.

**Comment by BinuDR** [comment]
Sheltim will take a look at it and merge it if it's good.  Thanks!
