### ISSUE TITLE
latest version of Lich will not run with Genie Switch

### ISSUE THREAD

**Issue by jsangeorzan** [rcuhljr/dr-lich#7]
Running as Admin Command Prompt

Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>ruby C:\lich\lich.rbw --dragonrealms --genie
C:/lich/lich.rbw:5: syntax error, unexpected '<'
<!DOCTYPE html>
 ^
C:/lich/lich.rbw:6: syntax error, unexpected '<'
<html lang="en" class=" is-copy-enabled is-u2f-enabled">
 ^
C:/lich/lich.rbw:6: syntax error, unexpected keyword_class, expecting end-of-input
<html lang="en" class=" is-copy-enabled is-u2f-enabled">
                     ^

C:\WINDOWS\system32>

**Comment by rcuhljr** [comment]
If you want to do the install manually instead of using the ;e toggle_lich_fork command, make sure you get the raw file, not the html page containing the file. https://raw.githubusercontent.com/rcuhljr/dr-lich/master/lich.rbw
